main: com.gmail.stefvanschiedev.buildinggame.Main
name: BuildingGame_Addon
version: 4.0.1
depend: [SocketAPI]

commands:
  bg:
    description: "Main BuildingGame command"
  buildinggame:
    description: "Main BuildingGame command"