language: java
jdk: openjdk11
sudo: true

before_install:
  - chmod +x ./scripts/install-dependencies.sh

install:
  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
  - java -jar BuildTools.jar --rev 1.13.1
  - wget https://www.robindebaets.be/LeaderHeadsAPI.jar
  - mvn install:install-file -Dfile=LeaderHeadsAPI.jar -DgroupId=me.robin -DartifactId=leaderheads -Dversion=3.1.6 -Dpackaging=jar
  - jdk_switcher use openjdk8
  - git clone https://github.com/Gnat008/perworldinventory-kt.git
  - cd perworldinventory-kt
  - mvn clean install
  - cd ../
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
  - git clone https://github.com/I-Al-Istannen/MiniNBT.git
  - cd MiniNBT
  - mvn clean install

script:
  - cd buildinggame
  - mvn clean install